# Generated by Django 4.2.5 on 2023-09-25 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="artist",
            table="Artist",
        ),
    ]
